name: Steam Price Tracker

on:
  schedule:
    - cron: '0 12 * * *'  # runs at 5PM ET 12AM UTC https://crontab.guru/
  workflow_dispatch:  # Allows manual trigger

jobs:
  track-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Steam Price Tracker
        run: python tracker.py  # Ensure this matches your script name

      - name: Commit and Push Price Updates
        run: |
          git config --global user.name "encs16"
          git config --global user.email "encs16@users.noreply.github.com"
          git add steam_prices.json notification.txt
          git commit -m "Update Steam prices" || echo "No changes to commit"
          git push
